### ISSUE TITLE
User Location from Google Maps

### ISSUE THREAD

**Issue by SamuelLangenfeld** [DataKind-DC/homelessness-service-navigator#31]
We're going to need to be able to access the user's location with their consent. I'm not sure what goes into this so it may take some research.

**Comment by jodebane** [comment]
https://www.npmjs.com/package/react-geolocated

**Comment by sfongx** [comment]
So I installed react-geolocated and tried this out just now.  I'm not able to get past the prerequisite of isGeolocationEnabled, and I'm getting the "Your browser does not support Geolocation" message (even though that shouldn't be the case). My export class Map code looks like the following:

```
export class Map extends React.PureComponent {

  render() {
    return !this.props.isGeolocationAvailable
      ? <div>Your browser does not support Geolocation</div>
      : !this.props.isGeolocationEnabled
        ? <div>Geolocation is not enabled</div>
        : <MyMapComponent
        lat={this.props.coords.latitude}
        long={this.props.coords.longitude} /> ;    
  }
}

```

**Comment by sfongx** [comment]
So, I've been playing around with this and discovered an obvious problem: all of the geolocation props have to get passed into the map component somehow, and I don't think the example from that link is clear as to how it happens. Based on how I attempted it earlier, I was essentially trying to access undefined props. That's why it was telling me "geolocation is not supported" because this.props.isGeolocationEnabled is undefined.
